In [ ]:
function mat_from_file(filepath)
    f = open(filepath, "r")
    lines = readlines(f)
    close(f)

    n, l = split(lines[1])
    n = parse(Int64, n)
    l = parse(Int64, l)

    mat = zeros(n, n)

    for i in 2:length(lines)
        i1, j1, val = split(lines[i])
        i1 = parse(Int64, i1)
        j1 = parse(Int64, j1)
        val = parse(Float64, val)
        mat[i1, j1] = val
    end

    return mat
end

In [ ]:
function vec_from_file(filepath)
    f = open(filepath, "r")
    lines = readlines(f)
    close(f)

    n = parse(Int64, lines[1])

    vec = zeros(n)

    for i in 2:length(lines)
        val = parse(Float64, lines[i])
        vec[i - 1] = val
    end

    return vec
end

In [29]:
function LU!(a, n)
    for k in 1:n-1
        for i in k+1:n
            a[i, k] = a[i, k] / a[k, k]
            for j in k+1:n
                a[i, j] = a[i, j] - a[i, k] * a[k, j]
            end
        end
    end

    return a
end

function LUxb(a, n, b)
    x = zeros(n)

    # Ly = b
    for k in 1:n
        x[k] = b[k]
        for i in 1:k-1
            x[k] = x[k] - a[k, i] * x[i]
        end
    end

    # Ux = y
    for k in reverse(1:n)
        for i in k+1:n
            x[k] = x[k] - a[k, i] * x[i]
        end
        x[k] = x[k] / a[k, k]
    end

    return x
end

LUxb (generic function with 1 method)

In [46]:
A = mat_from_file("../dane/dane16_1_1/A.txt")
b = vec_from_file("../dane/dane16_1_1/b.txt")

x = A \ b
show(stdout, "text/plain", A)

16×16 Matrix{Float64}:
  0.37517     1.36991   4.5534    -3.53688      0.00983523   0.0        0.0         0.0         0.0        0.0        0.0         0.0         0.0       0.0         0.0        0.0
 -1.30281    -4.35903   0.871167   7.34207      0.0          0.175106   0.0         0.0         0.0        0.0        0.0         0.0         0.0       0.0         0.0        0.0
  4.75774    -2.09952   1.7244    -1.67618      0.0          0.0        0.0159132   0.0         0.0        0.0        0.0         0.0         0.0       0.0         0.0        0.0
  0.0535187   5.52435  -5.13303   -3.31049      0.0          0.0        0.0         0.284416    0.0        0.0        0.0         0.0         0.0       0.0         0.0        0.0
  0.0         0.0       0.0        0.243349    -2.64842     -2.48366    3.27421    -0.188398    0.101303   0.0        0.0         0.0         0.0       0.0         0.0        0.0
  0.0         0.0       0.0        0.0522578   -6.74525      3.08946   -0.509293  

  -2.95201    -2.64518    5.26449
  0.0         0.0       0.0        0.0          0.0          0.0        0.0         0.0         0.0        0.0        0.0         0.168997   -2.29919   4.02429     1.3353    -1.66672
  0.0         0.0       0.0        0.0          0.0          0.0        0.0         0.0         0.0        0.0        0.0         0.0311943  -1.43456  -1.37421     7.798     -0.247148

In [32]:
A = mat_from_file("../dane/dane16_1_1/A.txt")
b = vec_from_file("../dane/dane16_1_1/b.txt")

#calculate LU
x = LUxb(LU!(A, 16), 16, b)

print(x)


[0.9999999999999608, 1.000000000000004, 0.9999999999999988, 0.9999999999999957, 1.0, 0.9999999999999991, 0.9999999999999997, 0.9999999999999998, 1.0000000000000002, 1.0, 1.0000000000000002, 1.0000000000000002, 1.0000000000000002, 1.0, 1.0, 1.0000000000000002]

In [43]:
A = mat_from_file("../dane/dane16_1_1/A.txt")
show(stdout, "text/plain", A)
LU!(A, 16)
show(stdout, "text/plain", A)

16×16 Matrix{Float64}:
  0.37517     1.36991   4.5534    -3.53688      0.00983523   0.0        0.0         0.0         0.0        0.0        0.0         0.0         0.0       0.0         0.0        0.0
 -1.30281    -4.35903   0.871167   7.34207      0.0          0.175106   0.0         0.0         0.0        0.0        0.0         0.0         0.0       0.0         0.0        0.0
  4.75774    -2.09952   1.7244    -1.67618      0.0          0.0        0.0159132   0.0         0.0        0.0        0.0         0.0         0.0       0.0         0.0        0.0
  0.0535187   5.52435  -5.13303   -3.31049      0.0          0.0        0.0         0.284416    0.0        0.0        0.0         0.0         0.0       0.0         0.0        0.0
  0.0         0.0       0.0        0.243349    -2.64842     -2.48366    3.27421    -0.188398    0.101303   0.0        0.0         0.0         0.0       0.0         0.0        0.0
  0.0         0.0       0.0        0.0522578   -6.74525      3.08946   -0.509293  

In [41]:
using LinearAlgebra
A = mat_from_file("../dane/dane16_1_1/A.txt")

l = lu(A)

LU!(A, 16)

show(stdout, "text/plain", A)
show(stdout, "text/plain", l.U)

16×16 Matrix{Float64}:
  0.37517     1.36991     4.5534      -3.53688       0.00983523   0.0        0.0          0.0          0.0         0.0          0.0         0.0          0.0         0.0           0.0         0.0
 -3.47258     0.398101   16.6832      -4.94006       0.0341537    0.175106   0.0          0.0          0.0         0.0          0.0         0.0          0.0         0.0           0.0         0.0
 12.6816    -48.9125    759.999     -198.453         1.54581      8.56486    0.0159132    0.0          0.0         0.0          0.0         0.0          0.0         0.0           0.0         0.0
  0.142652   13.3859     -0.301451     3.49706       0.00740748   0.23794    0.00479705   0.284416     0.0         0.0          0.0         0.0          0.0         0.0           0.0         0.0
  0.0         0.0         0.0          0.0695868    -2.64894     -2.50022    3.27387     -0.20819      0.101303    0.0          0.0         0.0          0.0         0.0           0.0         0.0
  